### Variables 
@apiurl = http://localhost:3333
@token = {{ authenticate.response.body.access_token }}

# @name create_account
POST {{apiurl}}/accounts
Content-Type: application/json

{
  "name": "Vinicius",
  "email": "vinicius@email.com",
  "password": "123456"
}

###

# @name authenticate
POST {{apiurl}}/sessions
Content-Type: application/json

{
  "email": "vinicius@email.com",
  "password": "123456" 
}

###

POST {{apiurl}}/questions
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "title": "Qual a cor do céu?",
  "description": "Gostaria de saber a cor do céu"
}