### Variables 
@apiurl = http://localhost:3333

POST {{apiurl}}/accounts
Content-Type: application/json

{
  "name": "Vinicius",
  "email": "vinicius@email.com",
  "password": "123456"
}

###

POST {{apiurl}}/sessions
Content-Type: application/json

{
  "email": "vinicius@email.com",
  "password": "123456" 
}